
package com.kyle.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloSOAP", targetNamespace = "http://soap.kyle.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloSOAP {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://soap.kyle.com/HelloSOAP/sayHelloRequest", output = "http://soap.kyle.com/HelloSOAP/sayHelloResponse")
	public String sayHello(@WebParam(name = "arg0", partName = "arg0") String arg0);

}
